Repository InovexSolutions/Kratos, pull requests merged in 2025-03, with the labels that each got.

#5 Update README.md to reflect project name change and enhance instructions
  README.md
Labels: documentation

#6 Upload .env.example for otehr users to use
  .env.example
Labels: documentation

#8 Add Pterodactyl server management APIs, update admin layout, and inte…
  components/admin/Navbar.vue
  layouts/admin.vue
  package.json
  pages/admin/index.vue
  pages/admin/management/datacenters.vue
  pages/admin/management/hosts.vue
  pages/admin/management/pricingPlans.vue
  pages/admin/pterodactyl/index.vue
  pages/admin/pterodactyl/index2.vue
  plugins/vue3-toastify.ts
  pnpm-lock.yaml
  prisma/migrations/20250320022333_add_ptero_table/migration.sql
  prisma/schema.prisma
  server/api/admin/hosts/[id].put.ts
  server/api/admin/hosts/index.post.ts
  server/api/admin/pterodactyl-servers/[id].delete.ts
  server/api/admin/pterodactyl-servers/[id].put.ts
  server/api/admin/pterodactyl-servers/eggs.get.ts
  server/api/admin/pterodactyl-servers/index.get.ts
  server/api/admin/pterodactyl-servers/index.post.ts
  server/api/admin/pterodactyl-servers/nests.get.ts
  server/api/admin/pterodactyl/servers.get.ts
  server/api/admin/stats.get.ts
  server/api/admin/users/index.get.ts
  server/services/pterodactyl.ts
Labels: enhancement

#15 Fix NavBar dropdown and remove deprecated Pterodactyl management page
  components/shared/NavBar.vue
  pages/admin/management/datacenters.vue
  pages/admin/management/hosts.vue
  pages/admin/pterodactyl/index2.vue
Labels: bug

#23 Add docker #22
  .dockerignore
  .github/workflows/ci-cd.yml
  Dockerfile
  docker-compose.yml
  nuxt.config.ts
  package.json
  plugins/pterodactyl.client.ts
  plugins/stripe.client.ts
  pnpm-lock.yaml
  server/api/auth/[...].ts
  server/services/pterodactyl.ts
Labels: enhancement

#24 Create FUNDING.yml
  .github/FUNDING.yml
Labels: documentation
